orbs:
  azure-cli: circleci/azure-cli@1.1.0
  azure-acr: circleci/azure-acr@0.2.1
  node: circleci/node@5.0.2
  
jobs:
  deploy-qa:
    machine:
      enabled: true
    steps:
      - run:
          name: Deploying-Qa
          command: ssh azureuser@172.174.187.175 './node-frontend-qa.sh';
version: 2.1
workflows:
  build_and_deploy_qa:
    jobs:       
      - azure-acr/build-and-push-image:
          login-server-name: $AZURE_ACR_LOGIN
          registry-name: $AZURE_REGISTRY
          dockerfile: application/Env/QA/Frontend/Dockerfile
          path:
          repo: sc-frontend-qa
          tag: 'latest,0.1$CIRCLE_BUILD_NUM'
          filters:
            branches:
              only: sc-qa-frontend
      - deploy-qa:
          requires:
            - azure-acr/build-and-push-image
          filters:
            branches:
              only: sc-qa-frontend
