export const DeviceDum = [
  {
    id: "1",
    deviceName: "device 1",
    deviceType: "device type 1",
    version: "device version 1",
    site: "device site 1",
    zone: "dveice zone 1",
    description: "dveice description 1",
    status: "Active",
  },
  {
    id: "2",
    deviceName: "device 2",
    deviceType: "device type 2",
    version: "device version 2",
    site: "device site 2",
    zone: "dveice zone 2",
    description: "dveice description 2",
    status: "Active",
  },
  {
    id: "3",
    deviceName: "device 3",
    deviceType: "device type 3",
    version: "device version 3",
    site: "device site 3",
    zone: "dveice zone 3",
    description: "dveice description 3",
    status: "Active",
  },
  {
    id: "4",
    deviceName: "device 4",
    deviceType: "device type 4",
    version: "device version 4",
    site: "device site 4",
    zone: "dveice zone 4",
    description: "dveice description 4",
    status: "Active",
  },
  {
    id: "5",
    deviceName: "device 5",
    deviceType: "device type 5",
    version: "device version 5",
    site: "device site 5",
    zone: "dveice zone 5",
    description: "dveice description 5",
    status: "Active",
  },
  {
    id: "6",
    deviceName: "device 6",
    deviceType: "device type 6",
    version: "device version 6",
    site: "device site 6",
    zone: "dveice zone 6",
    description: "dveice description 6",
    status: "Active",
  },
  {
    id: "7",
    deviceName: "device 7",
    deviceType: "device type 7",
    version: "device version 7",
    site: "device site 7",
    zone: "dveice zone 7",
    description: "dveice description 7",
    status: "Active",
  },
  {
    id: "8",
    deviceName: "device 8",
    deviceType: "device type 8",
    version: "device version 8",
    site: "device site 8",
    zone: "dveice zone 8",
    description: "dveice description 8",
    status: "Active",
  },
  {
    id: "9",
    deviceName: "device 9",
    deviceType: "device type 9",
    version: "device version 9",
    site: "device site 9",
    zone: "dveice zone 9",
    description: "dveice description 9",
    status: "Active",
  },
  {
    id: "10",
    deviceName: "device 10",
    deviceType: "device type 10",
    version: "device version 10",
    site: "device site 10",
    zone: "dveice zone 10",
    description: "dveice description 10",
    status: "Active",
  },
  {
    id: "11",
    deviceName: "device 11",
    deviceType: "device type 11",
    version: "device version 11",
    site: "device site 11",
    zone: "dveice zone 11",
    description: "dveice description 11",
    status: "Active",
  },
  {
    id: "12",
    deviceName: "device 12",
    deviceType: "device type 12",
    version: "device version 12",
    site: "device site 12",
    zone: "dveice zone 12",
    description: "dveice description 12",
    status: "Active",
  },
  {
    id: "13",
    deviceName: "device 13",
    deviceType: "device type 13",
    version: "device version 13",
    site: "device site 13",
    zone: "dveice zone 13",
    description: "dveice description 13",
    status: "Active",
  },
];
